# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dan_app_cfg_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1644, 835)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(600, 23))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #a0a0a0; /* 设置背景颜色为灰色 */\n"
"    border-radius: 10px; /* 设置边框圆角的半径为10px */\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setContentsMargins(11, 0, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_26 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(0, 20))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_26.setStyleSheet("font: 11pt \"Calibri\";\n"
"font-weight: 600; /* 设置字体粗细为600 */")
        self.label_26.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_6.addWidget(self.label_26)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pushButton_58 = QtWidgets.QPushButton(self.frame)
        self.pushButton_58.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_58.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_58.setStyleSheet("QPushButton {\n"
"    background-color: #3072B3; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #145289; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5591D2; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E5A97; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_58.setObjectName("pushButton_58")
        self.horizontalLayout_6.addWidget(self.pushButton_58)
        self.pushButton_59 = QtWidgets.QPushButton(self.frame)
        self.pushButton_59.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_59.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_59.setStyleSheet("QPushButton {\n"
"    background-color: #3b8303; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #326703; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #459403; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #397303; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_59.setObjectName("pushButton_59")
        self.horizontalLayout_6.addWidget(self.pushButton_59)
        self.verticalLayout.addWidget(self.frame)
        self.tableWidget_appCfgRegBlock = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_appCfgRegBlock.setMaximumSize(QtCore.QSize(600, 16777215))
        self.tableWidget_appCfgRegBlock.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 2px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.tableWidget_appCfgRegBlock.setObjectName("tableWidget_appCfgRegBlock")
        self.tableWidget_appCfgRegBlock.setColumnCount(5)
        self.tableWidget_appCfgRegBlock.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_appCfgRegBlock.setItem(4, 0, item)
        self.tableWidget_appCfgRegBlock.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget_appCfgRegBlock)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(600, 23))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #a0a0a0; /* 设置背景颜色为灰色 */\n"
"    border-radius: 10px; /* 设置边框圆角的半径为10px */\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_8.setContentsMargins(11, 0, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(0, 20))
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_28.setStyleSheet("font: 11pt \"Calibri\";\n"
"font-weight: 600; /* 设置字体粗细为600 */")
        self.label_28.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_8.addWidget(self.label_28)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.pushButton_62 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_62.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_62.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_62.setStyleSheet("QPushButton {\n"
"    background-color: #3072B3; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #145289; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5591D2; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E5A97; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_62.setObjectName("pushButton_62")
        self.horizontalLayout_8.addWidget(self.pushButton_62)
        self.pushButton_63 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_63.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_63.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_63.setStyleSheet("QPushButton {\n"
"    background-color: #3b8303; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #326703; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #459403; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #397303; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_63.setObjectName("pushButton_63")
        self.horizontalLayout_8.addWidget(self.pushButton_63)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.tableWidget_alertCfgRegBlock = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_alertCfgRegBlock.setMaximumSize(QtCore.QSize(600, 16777215))
        self.tableWidget_alertCfgRegBlock.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 2px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.tableWidget_alertCfgRegBlock.setObjectName("tableWidget_alertCfgRegBlock")
        self.tableWidget_alertCfgRegBlock.setColumnCount(5)
        self.tableWidget_alertCfgRegBlock.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alertCfgRegBlock.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alertCfgRegBlock.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alertCfgRegBlock.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alertCfgRegBlock.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alertCfgRegBlock.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alertCfgRegBlock.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alertCfgRegBlock.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alertCfgRegBlock.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alertCfgRegBlock.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alertCfgRegBlock.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alertCfgRegBlock.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alertCfgRegBlock.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alertCfgRegBlock.setItem(3, 0, item)
        self.tableWidget_alertCfgRegBlock.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget_alertCfgRegBlock)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 23))
        self.frame_4.setStyleSheet("QFrame {\n"
"    background-color: #a0a0a0; /* 设置背景颜色为灰色 */\n"
"    border-radius: 10px; /* 设置边框圆角的半径为10px */\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setContentsMargins(11, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_25 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(0, 20))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_25.setStyleSheet("font: 11pt \"Calibri\";\n"
"font-weight: 600; /* 设置字体粗细为600 */")
        self.label_25.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_5.addWidget(self.label_25)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.pushButton_56 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_56.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_56.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_56.setStyleSheet("QPushButton {\n"
"    background-color: #3072B3; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #145289; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5591D2; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E5A97; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_56.setObjectName("pushButton_56")
        self.horizontalLayout_5.addWidget(self.pushButton_56)
        self.pushButton_57 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_57.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_57.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_57.setStyleSheet("QPushButton {\n"
"    background-color: #3b8303; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #326703; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #459403; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #397303; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_57.setObjectName("pushButton_57")
        self.horizontalLayout_5.addWidget(self.pushButton_57)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.tableWidget_thresholdRegBlock = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_thresholdRegBlock.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget_thresholdRegBlock.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 2px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.tableWidget_thresholdRegBlock.setObjectName("tableWidget_thresholdRegBlock")
        self.tableWidget_thresholdRegBlock.setColumnCount(7)
        self.tableWidget_thresholdRegBlock.setRowCount(14)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_thresholdRegBlock.setItem(4, 0, item)
        self.tableWidget_thresholdRegBlock.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tableWidget_thresholdRegBlock)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 23))
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color: #a0a0a0; /* 设置背景颜色为灰色 */\n"
"    border-radius: 10px; /* 设置边框圆角的半径为10px */\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_7.setContentsMargins(11, 0, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(0, 20))
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_27.setStyleSheet("font: 11pt \"Calibri\";\n"
"font-weight: 600; /* 设置字体粗细为600 */")
        self.label_27.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_7.addWidget(self.label_27)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.pushButton_60 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_60.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_60.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_60.setStyleSheet("QPushButton {\n"
"    background-color: #3072B3; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #145289; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5591D2; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E5A97; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_60.setObjectName("pushButton_60")
        self.horizontalLayout_7.addWidget(self.pushButton_60)
        self.pushButton_61 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_61.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_61.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_61.setStyleSheet("QPushButton {\n"
"    background-color: #3b8303; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #326703; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #459403; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #397303; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_61.setObjectName("pushButton_61")
        self.horizontalLayout_7.addWidget(self.pushButton_61)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.tableWidget_acquisitionRegBlock = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_acquisitionRegBlock.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 2px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.tableWidget_acquisitionRegBlock.setObjectName("tableWidget_acquisitionRegBlock")
        self.tableWidget_acquisitionRegBlock.setColumnCount(11)
        self.tableWidget_acquisitionRegBlock.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_acquisitionRegBlock.setItem(3, 0, item)
        self.tableWidget_acquisitionRegBlock.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.tableWidget_acquisitionRegBlock)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1644, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_26.setText(_translate("MainWindow", "APPLICATION CONFIGURATION Register Block"))
        self.pushButton_58.setText(_translate("MainWindow", "CONFIGURE"))
        self.pushButton_59.setText(_translate("MainWindow", "READ BACK"))
        item = self.tableWidget_appCfgRegBlock.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_appCfgRegBlock.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_appCfgRegBlock.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_appCfgRegBlock.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_appCfgRegBlock.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_appCfgRegBlock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidget_appCfgRegBlock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Register"))
        item = self.tableWidget_appCfgRegBlock.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Pending (hex)"))
        item = self.tableWidget_appCfgRegBlock.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Device 0 (hex)"))
        item = self.tableWidget_appCfgRegBlock.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Device 1 (hex)"))
        __sortingEnabled = self.tableWidget_appCfgRegBlock.isSortingEnabled()
        self.tableWidget_appCfgRegBlock.setSortingEnabled(False)
        item = self.tableWidget_appCfgRegBlock.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_appCfgRegBlock.item(1, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_appCfgRegBlock.item(2, 0)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_appCfgRegBlock.item(3, 0)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_appCfgRegBlock.item(4, 0)
        item.setText(_translate("MainWindow", "5"))
        self.tableWidget_appCfgRegBlock.setSortingEnabled(__sortingEnabled)
        self.label_28.setText(_translate("MainWindow", "ALERT CONFIGURATION Register Block"))
        self.pushButton_62.setText(_translate("MainWindow", "CONFIGURE"))
        self.pushButton_63.setText(_translate("MainWindow", "READ BACK"))
        item = self.tableWidget_alertCfgRegBlock.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_alertCfgRegBlock.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_alertCfgRegBlock.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_alertCfgRegBlock.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_alertCfgRegBlock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidget_alertCfgRegBlock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Register"))
        item = self.tableWidget_alertCfgRegBlock.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Pending (hex)"))
        item = self.tableWidget_alertCfgRegBlock.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Device 0 (hex)"))
        item = self.tableWidget_alertCfgRegBlock.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Device 1 (hex)"))
        __sortingEnabled = self.tableWidget_alertCfgRegBlock.isSortingEnabled()
        self.tableWidget_alertCfgRegBlock.setSortingEnabled(False)
        item = self.tableWidget_alertCfgRegBlock.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_alertCfgRegBlock.item(1, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_alertCfgRegBlock.item(2, 0)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_alertCfgRegBlock.item(3, 0)
        item.setText(_translate("MainWindow", "4"))
        self.tableWidget_alertCfgRegBlock.setSortingEnabled(__sortingEnabled)
        self.label_25.setText(_translate("MainWindow", "THRESHOLD Register Block"))
        self.pushButton_56.setText(_translate("MainWindow", "CONFIGURE"))
        self.pushButton_57.setText(_translate("MainWindow", "READ BACK"))
        item = self.tableWidget_thresholdRegBlock.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_thresholdRegBlock.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_thresholdRegBlock.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_thresholdRegBlock.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_thresholdRegBlock.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_thresholdRegBlock.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_thresholdRegBlock.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_thresholdRegBlock.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_thresholdRegBlock.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_thresholdRegBlock.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_thresholdRegBlock.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_thresholdRegBlock.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget_thresholdRegBlock.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget_thresholdRegBlock.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget_thresholdRegBlock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidget_thresholdRegBlock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Register"))
        item = self.tableWidget_thresholdRegBlock.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Pending (hex)"))
        item = self.tableWidget_thresholdRegBlock.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Device 0 (hex)"))
        item = self.tableWidget_thresholdRegBlock.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Device 1 (hex)"))
        item = self.tableWidget_thresholdRegBlock.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "新建列"))
        item = self.tableWidget_thresholdRegBlock.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        __sortingEnabled = self.tableWidget_thresholdRegBlock.isSortingEnabled()
        self.tableWidget_thresholdRegBlock.setSortingEnabled(False)
        item = self.tableWidget_thresholdRegBlock.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_thresholdRegBlock.item(1, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_thresholdRegBlock.item(2, 0)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_thresholdRegBlock.item(3, 0)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_thresholdRegBlock.item(4, 0)
        item.setText(_translate("MainWindow", "5"))
        self.tableWidget_thresholdRegBlock.setSortingEnabled(__sortingEnabled)
        self.label_27.setText(_translate("MainWindow", "ACQUISITION Register Block"))
        self.pushButton_60.setText(_translate("MainWindow", "CONFIGURE"))
        self.pushButton_61.setText(_translate("MainWindow", "READ BACK"))
        item = self.tableWidget_acquisitionRegBlock.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_acquisitionRegBlock.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_acquisitionRegBlock.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_acquisitionRegBlock.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_acquisitionRegBlock.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidget_acquisitionRegBlock.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Register"))
        item = self.tableWidget_acquisitionRegBlock.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Pending (hex)"))
        item = self.tableWidget_acquisitionRegBlock.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Device 0 (hex)"))
        item = self.tableWidget_acquisitionRegBlock.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Device 1 (hex)"))
        item = self.tableWidget_acquisitionRegBlock.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "新建列"))
        item = self.tableWidget_acquisitionRegBlock.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_acquisitionRegBlock.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_acquisitionRegBlock.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_acquisitionRegBlock.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_acquisitionRegBlock.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        __sortingEnabled = self.tableWidget_acquisitionRegBlock.isSortingEnabled()
        self.tableWidget_acquisitionRegBlock.setSortingEnabled(False)
        item = self.tableWidget_acquisitionRegBlock.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_acquisitionRegBlock.item(1, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_acquisitionRegBlock.item(2, 0)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_acquisitionRegBlock.item(3, 0)
        item.setText(_translate("MainWindow", "4"))
        self.tableWidget_acquisitionRegBlock.setSortingEnabled(__sortingEnabled)
