# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dan_chain_cfg_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1706, 1011)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 23))
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color: #a0a0a0; /* 设置背景颜色为灰色 */\n"
"    border-radius: 10px; /* 设置边框圆角的半径为10px */\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(0, 20))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_23.setStyleSheet("font: 11pt \"Calibri\";\n"
"font-weight: 600; /* 设置字体粗细为600 */")
        self.label_23.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        spacerItem = QtWidgets.QSpacerItem(447, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_singleAfe = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_singleAfe.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton_singleAfe.setMaximumSize(QtCore.QSize(16777215, 20))
        self.radioButton_singleAfe.setStyleSheet("font: 10pt \"Calibri\";\n"
"font-weight: 600; /* 设置字体粗细为600 */")
        self.radioButton_singleAfe.setObjectName("radioButton_singleAfe")
        self.verticalLayout.addWidget(self.radioButton_singleAfe)
        self.radioButton_dualAfe = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_dualAfe.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton_dualAfe.setMaximumSize(QtCore.QSize(16777215, 20))
        self.radioButton_dualAfe.setStyleSheet("font: 10pt \"Calibri\";\n"
"font-weight: 600; /* 设置字体粗细为600 */")
        self.radioButton_dualAfe.setObjectName("radioButton_dualAfe")
        self.verticalLayout.addWidget(self.radioButton_dualAfe)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 23))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #a0a0a0; /* 设置背景颜色为灰色 */\n"
"    border-radius: 10px; /* 设置边框圆角的半径为10px */\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_21 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(0, 20))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_21.setStyleSheet("font: 11pt \"Calibri\";\n"
"font-weight: 600; /* 设置字体粗细为600 */")
        self.label_21.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        spacerItem1 = QtWidgets.QSpacerItem(447, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_uartIfConf = QtWidgets.QPushButton(self.frame)
        self.pushButton_uartIfConf.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_uartIfConf.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_uartIfConf.setStyleSheet("QPushButton {\n"
"    background-color: #3072B3; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #145289; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5591D2; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E5A97; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_uartIfConf.setObjectName("pushButton_uartIfConf")
        self.horizontalLayout.addWidget(self.pushButton_uartIfConf)
        self.pushButton_uartIfReadBack = QtWidgets.QPushButton(self.frame)
        self.pushButton_uartIfReadBack.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_uartIfReadBack.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_uartIfReadBack.setStyleSheet("QPushButton {\n"
"    background-color: #3b8303; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #326703; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #459403; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #397303; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_uartIfReadBack.setObjectName("pushButton_uartIfReadBack")
        self.horizontalLayout.addWidget(self.pushButton_uartIfReadBack)
        self.verticalLayout_2.addWidget(self.frame)
        self.table_chainCfg_uartIfCfg = QtWidgets.QTableWidget(self.centralwidget)
        self.table_chainCfg_uartIfCfg.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 5px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.table_chainCfg_uartIfCfg.setObjectName("table_chainCfg_uartIfCfg")
        self.table_chainCfg_uartIfCfg.setColumnCount(14)
        self.table_chainCfg_uartIfCfg.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_chainCfg_uartIfCfg.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_chainCfg_uartIfCfg.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfCfg.setItem(2, 3, item)
        self.table_chainCfg_uartIfCfg.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.table_chainCfg_uartIfCfg)
        self.table_chainCfg_uartIfAddr = QtWidgets.QTableWidget(self.centralwidget)
        self.table_chainCfg_uartIfAddr.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 5px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.table_chainCfg_uartIfAddr.setObjectName("table_chainCfg_uartIfAddr")
        self.table_chainCfg_uartIfAddr.setColumnCount(8)
        self.table_chainCfg_uartIfAddr.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_chainCfg_uartIfAddr.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_chainCfg_uartIfAddr.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_uartIfAddr.setItem(2, 3, item)
        self.table_chainCfg_uartIfAddr.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.table_chainCfg_uartIfAddr)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 23))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #a0a0a0; /* 设置背景颜色为灰色 */\n"
"    border-radius: 10px; /* 设置边框圆角的半径为10px */\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(0, 20))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_22.setStyleSheet("font: 11pt \"Calibri\";\n"
"font-weight: 600; /* 设置字体粗细为600 */")
        self.label_22.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.lineEdit_warnStatusPwrUp = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_warnStatusPwrUp.setMinimumSize(QtCore.QSize(70, 0))
        self.lineEdit_warnStatusPwrUp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_warnStatusPwrUp.setFont(font)
        self.lineEdit_warnStatusPwrUp.setStyleSheet("QLineEdit {\n"
"  font: 8pt \"Calibri\"; /* 字体 */\n"
"  font-weight: 600; /* 字体粗细 */\n"
"  color: white; /* 文字颜色 */\n"
"  background-color: #ff0000; /* 按钮背景颜色 1*/\n"
"border-color: #ce4500; /* 边框颜色 3*/\n"
"border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"padding: 5px; /* 内边距 */\n"
"}")
        self.lineEdit_warnStatusPwrUp.setFrame(False)
        self.lineEdit_warnStatusPwrUp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_warnStatusPwrUp.setObjectName("lineEdit_warnStatusPwrUp")
        self.horizontalLayout_2.addWidget(self.lineEdit_warnStatusPwrUp)
        spacerItem3 = QtWidgets.QSpacerItem(447, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.table_chainCfg_statusBlk_pwrUpDev0 = QtWidgets.QTableWidget(self.centralwidget)
        self.table_chainCfg_statusBlk_pwrUpDev0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.table_chainCfg_statusBlk_pwrUpDev0.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 5px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.table_chainCfg_statusBlk_pwrUpDev0.setObjectName("table_chainCfg_statusBlk_pwrUpDev0")
        self.table_chainCfg_statusBlk_pwrUpDev0.setColumnCount(5)
        self.table_chainCfg_statusBlk_pwrUpDev0.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_chainCfg_statusBlk_pwrUpDev0.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 242, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.table_chainCfg_statusBlk_pwrUpDev0.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_chainCfg_statusBlk_pwrUpDev0.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev0.setItem(2, 3, item)
        self.table_chainCfg_statusBlk_pwrUpDev0.verticalHeader().setVisible(False)
        self.horizontalLayout_7.addWidget(self.table_chainCfg_statusBlk_pwrUpDev0)
        self.table_chainCfg_statusBlk_pwrUpDev1 = QtWidgets.QTableWidget(self.centralwidget)
        self.table_chainCfg_statusBlk_pwrUpDev1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.table_chainCfg_statusBlk_pwrUpDev1.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 5px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.table_chainCfg_statusBlk_pwrUpDev1.setObjectName("table_chainCfg_statusBlk_pwrUpDev1")
        self.table_chainCfg_statusBlk_pwrUpDev1.setColumnCount(2)
        self.table_chainCfg_statusBlk_pwrUpDev1.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_pwrUpDev1.setHorizontalHeaderItem(1, item)
        self.table_chainCfg_statusBlk_pwrUpDev1.verticalHeader().setVisible(False)
        self.horizontalLayout_7.addWidget(self.table_chainCfg_statusBlk_pwrUpDev1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 23))
        self.frame_6.setStyleSheet("QFrame {\n"
"    background-color: #a0a0a0; /* 设置背景颜色为灰色 */\n"
"    border-radius: 10px; /* 设置边框圆角的半径为10px */\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_24 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(0, 20))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_24.setStyleSheet("font: 11pt \"Calibri\";\n"
"font-weight: 600; /* 设置字体粗细为600 */")
        self.label_24.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_5.addWidget(self.label_24)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.lineEdit_warnStatusInit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_warnStatusInit.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEdit_warnStatusInit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_warnStatusInit.setFont(font)
        self.lineEdit_warnStatusInit.setStyleSheet("QLineEdit {\n"
"  font: 8pt \"Calibri\"; /* 字体 */\n"
"  font-weight: 600; /* 字体粗细 */\n"
"  color: white; /* 文字颜色 */\n"
"  background-color: #ff0000; /* 按钮背景颜色 1*/\n"
"border-color: #ce4500; /* 边框颜色 3*/\n"
"border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"padding: 5px; /* 内边距 */\n"
"}")
        self.lineEdit_warnStatusInit.setFrame(False)
        self.lineEdit_warnStatusInit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_warnStatusInit.setObjectName("lineEdit_warnStatusInit")
        self.horizontalLayout_5.addWidget(self.lineEdit_warnStatusInit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.pushButton_statusRegReInit = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_statusRegReInit.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_statusRegReInit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_statusRegReInit.setStyleSheet("QPushButton {\n"
"    background-color: #e84d00; /* 按钮背景颜色 1*/\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #ce4500; /* 边框颜色 3*/\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff5500; /* 悬停时的背景颜色 0*/\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df4a00; /* 按下时的背景颜色 2*/\n"
"}\n"
"")
        self.pushButton_statusRegReInit.setObjectName("pushButton_statusRegReInit")
        self.horizontalLayout_5.addWidget(self.pushButton_statusRegReInit)
        self.pushButton_statusRegClear = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_statusRegClear.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_statusRegClear.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_statusRegClear.setStyleSheet("QPushButton {\n"
"    background-color: #f3d22d; /* 按钮背景颜色 1*/\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #cbaf25; /* 边框颜色 3*/\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffdc2f; /* 悬停时的背景颜色 0*/\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d8bb28; /* 按下时的背景颜色 2*/\n"
"}\n"
"")
        self.pushButton_statusRegClear.setObjectName("pushButton_statusRegClear")
        self.horizontalLayout_5.addWidget(self.pushButton_statusRegClear)
        self.pushButton_statusRegInit = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_statusRegInit.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_statusRegInit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_statusRegInit.setStyleSheet("QPushButton {\n"
"    background-color: #3072B3; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #145289; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5591D2; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E5A97; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_statusRegInit.setObjectName("pushButton_statusRegInit")
        self.horizontalLayout_5.addWidget(self.pushButton_statusRegInit)
        self.pushButton_statusRegReadBack = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_statusRegReadBack.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_statusRegReadBack.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_statusRegReadBack.setStyleSheet("QPushButton {\n"
"    background-color: #3b8303; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #326703; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #459403; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #397303; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_statusRegReadBack.setObjectName("pushButton_statusRegReadBack")
        self.horizontalLayout_5.addWidget(self.pushButton_statusRegReadBack)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.table_chainCfg_statusBlk_initDev0 = QtWidgets.QTableWidget(self.centralwidget)
        self.table_chainCfg_statusBlk_initDev0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.table_chainCfg_statusBlk_initDev0.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 5px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.table_chainCfg_statusBlk_initDev0.setObjectName("table_chainCfg_statusBlk_initDev0")
        self.table_chainCfg_statusBlk_initDev0.setColumnCount(5)
        self.table_chainCfg_statusBlk_initDev0.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_chainCfg_statusBlk_initDev0.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_chainCfg_statusBlk_initDev0.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev0.setItem(2, 3, item)
        self.table_chainCfg_statusBlk_initDev0.horizontalHeader().setVisible(False)
        self.table_chainCfg_statusBlk_initDev0.verticalHeader().setVisible(False)
        self.horizontalLayout_6.addWidget(self.table_chainCfg_statusBlk_initDev0)
        self.table_chainCfg_statusBlk_initDev1 = QtWidgets.QTableWidget(self.centralwidget)
        self.table_chainCfg_statusBlk_initDev1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.table_chainCfg_statusBlk_initDev1.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 5px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.table_chainCfg_statusBlk_initDev1.setObjectName("table_chainCfg_statusBlk_initDev1")
        self.table_chainCfg_statusBlk_initDev1.setColumnCount(2)
        self.table_chainCfg_statusBlk_initDev1.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_initDev1.setHorizontalHeaderItem(1, item)
        self.table_chainCfg_statusBlk_initDev1.horizontalHeader().setVisible(False)
        self.table_chainCfg_statusBlk_initDev1.verticalHeader().setVisible(False)
        self.horizontalLayout_6.addWidget(self.table_chainCfg_statusBlk_initDev1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 23))
        self.frame_10.setStyleSheet("QFrame {\n"
"    background-color: #a0a0a0; /* 设置背景颜色为灰色 */\n"
"    border-radius: 10px; /* 设置边框圆角的半径为10px */\n"
"}\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_21.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_26 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(0, 20))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_26.setStyleSheet("font: 11pt \"Calibri\";\n"
"font-weight: 600; /* 设置字体粗细为600 */")
        self.label_26.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_21.addWidget(self.label_26)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem6)
        self.pushButton_statusRegReInit_3 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_statusRegReInit_3.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_statusRegReInit_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_statusRegReInit_3.setStyleSheet("QPushButton {\n"
"    background-color: #e84d00; /* 按钮背景颜色 1*/\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #ce4500; /* 边框颜色 3*/\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff5500; /* 悬停时的背景颜色 0*/\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df4a00; /* 按下时的背景颜色 2*/\n"
"}\n"
"")
        self.pushButton_statusRegReInit_3.setObjectName("pushButton_statusRegReInit_3")
        self.horizontalLayout_21.addWidget(self.pushButton_statusRegReInit_3)
        self.pushButton_statusRegClear_3 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_statusRegClear_3.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_statusRegClear_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_statusRegClear_3.setStyleSheet("QPushButton {\n"
"    background-color: #f3d22d; /* 按钮背景颜色 1*/\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #cbaf25; /* 边框颜色 3*/\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffdc2f; /* 悬停时的背景颜色 0*/\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d8bb28; /* 按下时的背景颜色 2*/\n"
"}\n"
"")
        self.pushButton_statusRegClear_3.setObjectName("pushButton_statusRegClear_3")
        self.horizontalLayout_21.addWidget(self.pushButton_statusRegClear_3)
        self.pushButton_statusRegInit_3 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_statusRegInit_3.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_statusRegInit_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_statusRegInit_3.setStyleSheet("QPushButton {\n"
"    background-color: #3072B3; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #145289; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5591D2; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E5A97; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_statusRegInit_3.setObjectName("pushButton_statusRegInit_3")
        self.horizontalLayout_21.addWidget(self.pushButton_statusRegInit_3)
        self.pushButton_statusRegReadBack_3 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_statusRegReadBack_3.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_statusRegReadBack_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_statusRegReadBack_3.setStyleSheet("QPushButton {\n"
"    background-color: #3b8303; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #326703; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #459403; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #397303; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_statusRegReadBack_3.setObjectName("pushButton_statusRegReadBack_3")
        self.horizontalLayout_21.addWidget(self.pushButton_statusRegReadBack_3)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.table_chainCfg_statusBlk_curDev0 = QtWidgets.QTableWidget(self.centralwidget)
        self.table_chainCfg_statusBlk_curDev0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.table_chainCfg_statusBlk_curDev0.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 5px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.table_chainCfg_statusBlk_curDev0.setObjectName("table_chainCfg_statusBlk_curDev0")
        self.table_chainCfg_statusBlk_curDev0.setColumnCount(5)
        self.table_chainCfg_statusBlk_curDev0.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_chainCfg_statusBlk_curDev0.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_chainCfg_statusBlk_curDev0.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev0.setItem(2, 3, item)
        self.table_chainCfg_statusBlk_curDev0.horizontalHeader().setVisible(False)
        self.table_chainCfg_statusBlk_curDev0.verticalHeader().setVisible(False)
        self.horizontalLayout_22.addWidget(self.table_chainCfg_statusBlk_curDev0)
        self.table_chainCfg_statusBlk_curDev1 = QtWidgets.QTableWidget(self.centralwidget)
        self.table_chainCfg_statusBlk_curDev1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.table_chainCfg_statusBlk_curDev1.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 5px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.table_chainCfg_statusBlk_curDev1.setObjectName("table_chainCfg_statusBlk_curDev1")
        self.table_chainCfg_statusBlk_curDev1.setColumnCount(2)
        self.table_chainCfg_statusBlk_curDev1.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_statusBlk_curDev1.setHorizontalHeaderItem(1, item)
        self.table_chainCfg_statusBlk_curDev1.horizontalHeader().setVisible(False)
        self.table_chainCfg_statusBlk_curDev1.verticalHeader().setVisible(False)
        self.horizontalLayout_22.addWidget(self.table_chainCfg_statusBlk_curDev1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 23))
        self.frame_8.setStyleSheet("QFrame {\n"
"    background-color: #a0a0a0; /* 设置背景颜色为灰色 */\n"
"    border-radius: 10px; /* 设置边框圆角的半径为10px */\n"
"}\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_20.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_25 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(0, 20))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_25.setStyleSheet("font: 11pt \"Calibri\";\n"
"font-weight: 600; /* 设置字体粗细为600 */")
        self.label_25.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_20.addWidget(self.label_25)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem7)
        self.pushButton_statusRegReInit_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_statusRegReInit_2.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_statusRegReInit_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_statusRegReInit_2.setStyleSheet("QPushButton {\n"
"    background-color: #e84d00; /* 按钮背景颜色 1*/\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #ce4500; /* 边框颜色 3*/\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff5500; /* 悬停时的背景颜色 0*/\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df4a00; /* 按下时的背景颜色 2*/\n"
"}\n"
"")
        self.pushButton_statusRegReInit_2.setObjectName("pushButton_statusRegReInit_2")
        self.horizontalLayout_20.addWidget(self.pushButton_statusRegReInit_2)
        self.pushButton_statusRegClear_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_statusRegClear_2.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_statusRegClear_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_statusRegClear_2.setStyleSheet("QPushButton {\n"
"    background-color: #f3d22d; /* 按钮背景颜色 1*/\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #cbaf25; /* 边框颜色 3*/\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffdc2f; /* 悬停时的背景颜色 0*/\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d8bb28; /* 按下时的背景颜色 2*/\n"
"}\n"
"")
        self.pushButton_statusRegClear_2.setObjectName("pushButton_statusRegClear_2")
        self.horizontalLayout_20.addWidget(self.pushButton_statusRegClear_2)
        self.pushButton_statusRegInit_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_statusRegInit_2.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_statusRegInit_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_statusRegInit_2.setStyleSheet("QPushButton {\n"
"    background-color: #3072B3; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #145289; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5591D2; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E5A97; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_statusRegInit_2.setObjectName("pushButton_statusRegInit_2")
        self.horizontalLayout_20.addWidget(self.pushButton_statusRegInit_2)
        self.pushButton_statusRegReadBack_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_statusRegReadBack_2.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_statusRegReadBack_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_statusRegReadBack_2.setStyleSheet("QPushButton {\n"
"    background-color: #3b8303; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #326703; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 8pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #459403; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #397303; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_statusRegReadBack_2.setObjectName("pushButton_statusRegReadBack_2")
        self.horizontalLayout_20.addWidget(self.pushButton_statusRegReadBack_2)
        self.verticalLayout_2.addWidget(self.frame_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.table_chainCfg_rstBlk_Dev0 = QtWidgets.QTableWidget(self.centralwidget)
        self.table_chainCfg_rstBlk_Dev0.setMaximumSize(QtCore.QSize(450, 16777215))
        self.table_chainCfg_rstBlk_Dev0.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 5px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.table_chainCfg_rstBlk_Dev0.setObjectName("table_chainCfg_rstBlk_Dev0")
        self.table_chainCfg_rstBlk_Dev0.setColumnCount(4)
        self.table_chainCfg_rstBlk_Dev0.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_rstBlk_Dev0.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_chainCfg_rstBlk_Dev0.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_rstBlk_Dev0.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_rstBlk_Dev0.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_rstBlk_Dev0.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_rstBlk_Dev0.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_rstBlk_Dev0.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_rstBlk_Dev0.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_rstBlk_Dev0.setItem(0, 3, item)
        self.table_chainCfg_rstBlk_Dev0.verticalHeader().setVisible(False)
        self.horizontalLayout_3.addWidget(self.table_chainCfg_rstBlk_Dev0)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.table_chainCfg_rstBlk_Dev1 = QtWidgets.QTableWidget(self.centralwidget)
        self.table_chainCfg_rstBlk_Dev1.setMaximumSize(QtCore.QSize(130, 16777215))
        self.table_chainCfg_rstBlk_Dev1.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 5px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.table_chainCfg_rstBlk_Dev1.setObjectName("table_chainCfg_rstBlk_Dev1")
        self.table_chainCfg_rstBlk_Dev1.setColumnCount(1)
        self.table_chainCfg_rstBlk_Dev1.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_rstBlk_Dev1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_rstBlk_Dev1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_chainCfg_rstBlk_Dev1.setItem(0, 0, item)
        self.table_chainCfg_rstBlk_Dev1.verticalHeader().setVisible(False)
        self.horizontalLayout_3.addWidget(self.table_chainCfg_rstBlk_Dev1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1706, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_23.setText(_translate("MainWindow", "Setup Option Selection"))
        self.radioButton_singleAfe.setText(_translate("MainWindow", "Single AFE Device"))
        self.radioButton_dualAfe.setText(_translate("MainWindow", "Dual AFE Daisy Chain"))
        self.label_21.setText(_translate("MainWindow", "UART Interface Configuration"))
        self.pushButton_uartIfConf.setText(_translate("MainWindow", "CONFIGURE"))
        self.pushButton_uartIfReadBack.setText(_translate("MainWindow", "READ BACK"))
        item = self.table_chainCfg_uartIfCfg.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.table_chainCfg_uartIfCfg.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_chainCfg_uartIfCfg.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.table_chainCfg_uartIfCfg.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.table_chainCfg_uartIfCfg.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Register"))
        item = self.table_chainCfg_uartIfCfg.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expected {hex}"))
        item = self.table_chainCfg_uartIfCfg.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actual {hex}"))
        item = self.table_chainCfg_uartIfCfg.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "UARTDUAL"))
        item = self.table_chainCfg_uartIfCfg.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "UARTLPBK"))
        item = self.table_chainCfg_uartIfCfg.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "UARTWRPATH"))
        item = self.table_chainCfg_uartIfCfg.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "TXUIDLEHIZ"))
        item = self.table_chainCfg_uartIfCfg.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "TXLIDLEHIZ"))
        item = self.table_chainCfg_uartIfCfg.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "UARTDCEN"))
        item = self.table_chainCfg_uartIfCfg.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "UARTALVCNTEN"))
        item = self.table_chainCfg_uartIfCfg.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "{logic Zero}"))
        item = self.table_chainCfg_uartIfCfg.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "DBLBUFEN"))
        item = self.table_chainCfg_uartIfCfg.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Reseved/SPI[6:0]"))
        __sortingEnabled = self.table_chainCfg_uartIfCfg.isSortingEnabled()
        self.table_chainCfg_uartIfCfg.setSortingEnabled(False)
        item = self.table_chainCfg_uartIfCfg.item(0, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_uartIfCfg.item(0, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Signle AFE)"))
        item = self.table_chainCfg_uartIfCfg.item(0, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_uartIfCfg.item(0, 3)
        item.setText(_translate("MainWindow", "A410"))
        item = self.table_chainCfg_uartIfCfg.item(1, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_uartIfCfg.item(1, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Dual, Device 0)"))
        item = self.table_chainCfg_uartIfCfg.item(1, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_uartIfCfg.item(1, 3)
        item.setText(_translate("MainWindow", "A410"))
        item = self.table_chainCfg_uartIfCfg.item(2, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_uartIfCfg.item(2, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Dual, Device 1)"))
        item = self.table_chainCfg_uartIfCfg.item(2, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_uartIfCfg.item(2, 3)
        item.setText(_translate("MainWindow", "A410"))
        self.table_chainCfg_uartIfCfg.setSortingEnabled(__sortingEnabled)
        item = self.table_chainCfg_uartIfAddr.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.table_chainCfg_uartIfAddr.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_chainCfg_uartIfAddr.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.table_chainCfg_uartIfAddr.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.table_chainCfg_uartIfAddr.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Register"))
        item = self.table_chainCfg_uartIfAddr.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expected {hex}"))
        item = self.table_chainCfg_uartIfAddr.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actual {hex}"))
        item = self.table_chainCfg_uartIfAddr.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "UARTDUAL"))
        item = self.table_chainCfg_uartIfAddr.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "UARTLPBK"))
        item = self.table_chainCfg_uartIfAddr.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "UARTWRPATH"))
        item = self.table_chainCfg_uartIfAddr.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "TXUIDLEHIZ"))
        __sortingEnabled = self.table_chainCfg_uartIfAddr.isSortingEnabled()
        self.table_chainCfg_uartIfAddr.setSortingEnabled(False)
        item = self.table_chainCfg_uartIfAddr.item(0, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_uartIfAddr.item(0, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Signle AFE)"))
        item = self.table_chainCfg_uartIfAddr.item(0, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_uartIfAddr.item(0, 3)
        item.setText(_translate("MainWindow", "A410"))
        item = self.table_chainCfg_uartIfAddr.item(1, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_uartIfAddr.item(1, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Dual, Device 0)"))
        item = self.table_chainCfg_uartIfAddr.item(1, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_uartIfAddr.item(1, 3)
        item.setText(_translate("MainWindow", "A410"))
        item = self.table_chainCfg_uartIfAddr.item(2, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_uartIfAddr.item(2, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Dual, Device 1)"))
        item = self.table_chainCfg_uartIfAddr.item(2, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_uartIfAddr.item(2, 3)
        item.setText(_translate("MainWindow", "A410"))
        self.table_chainCfg_uartIfAddr.setSortingEnabled(__sortingEnabled)
        self.label_22.setText(_translate("MainWindow", "General Summary Information (Power-Up)"))
        self.lineEdit_warnStatusPwrUp.setText(_translate("MainWindow", "WARNING: Uexpected Power-Up Status - Confirm Setup"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Register"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expected {hex}"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actual {hex}"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", " "))
        __sortingEnabled = self.table_chainCfg_statusBlk_pwrUpDev0.isSortingEnabled()
        self.table_chainCfg_statusBlk_pwrUpDev0.setSortingEnabled(False)
        item = self.table_chainCfg_statusBlk_pwrUpDev0.item(0, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.item(0, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Signle AFE)"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.item(0, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.item(0, 3)
        item.setText(_translate("MainWindow", "A410"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.item(1, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.item(1, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Dual, Device 0)"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.item(1, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.item(1, 3)
        item.setText(_translate("MainWindow", "A410"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.item(2, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.item(2, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Dual, Device 1)"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.item(2, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_statusBlk_pwrUpDev0.item(2, 3)
        item.setText(_translate("MainWindow", "A410"))
        self.table_chainCfg_statusBlk_pwrUpDev0.setSortingEnabled(__sortingEnabled)
        item = self.table_chainCfg_statusBlk_pwrUpDev1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.table_chainCfg_statusBlk_pwrUpDev1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_chainCfg_statusBlk_pwrUpDev1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.table_chainCfg_statusBlk_pwrUpDev1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.table_chainCfg_statusBlk_pwrUpDev1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Device1"))
        item = self.table_chainCfg_statusBlk_pwrUpDev1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "LED Array"))
        self.label_24.setText(_translate("MainWindow", "General Summary Information (Initialization)"))
        self.lineEdit_warnStatusInit.setText(_translate("MainWindow", "WARNING: Uexpected Post-Initialization Status - Confirm Setup"))
        self.pushButton_statusRegReInit.setText(_translate("MainWindow", "RE-INITIALIZE"))
        self.pushButton_statusRegClear.setText(_translate("MainWindow", "CLERA COMM"))
        self.pushButton_statusRegInit.setText(_translate("MainWindow", "INITIALIZE"))
        self.pushButton_statusRegReadBack.setText(_translate("MainWindow", "READ BACK"))
        item = self.table_chainCfg_statusBlk_initDev0.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.table_chainCfg_statusBlk_initDev0.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_chainCfg_statusBlk_initDev0.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.table_chainCfg_statusBlk_initDev0.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.table_chainCfg_statusBlk_initDev0.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.table_chainCfg_statusBlk_initDev0.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Register"))
        item = self.table_chainCfg_statusBlk_initDev0.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expected {hex}"))
        item = self.table_chainCfg_statusBlk_initDev0.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actual {hex}"))
        item = self.table_chainCfg_statusBlk_initDev0.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", " "))
        __sortingEnabled = self.table_chainCfg_statusBlk_initDev0.isSortingEnabled()
        self.table_chainCfg_statusBlk_initDev0.setSortingEnabled(False)
        item = self.table_chainCfg_statusBlk_initDev0.item(0, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_statusBlk_initDev0.item(0, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Signle AFE)"))
        item = self.table_chainCfg_statusBlk_initDev0.item(0, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_statusBlk_initDev0.item(0, 3)
        item.setText(_translate("MainWindow", "A410"))
        item = self.table_chainCfg_statusBlk_initDev0.item(1, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_statusBlk_initDev0.item(1, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Dual, Device 0)"))
        item = self.table_chainCfg_statusBlk_initDev0.item(1, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_statusBlk_initDev0.item(1, 3)
        item.setText(_translate("MainWindow", "A410"))
        item = self.table_chainCfg_statusBlk_initDev0.item(2, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_statusBlk_initDev0.item(2, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Dual, Device 1)"))
        item = self.table_chainCfg_statusBlk_initDev0.item(2, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_statusBlk_initDev0.item(2, 3)
        item.setText(_translate("MainWindow", "A410"))
        self.table_chainCfg_statusBlk_initDev0.setSortingEnabled(__sortingEnabled)
        item = self.table_chainCfg_statusBlk_initDev1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.table_chainCfg_statusBlk_initDev1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_chainCfg_statusBlk_initDev1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.table_chainCfg_statusBlk_initDev1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.table_chainCfg_statusBlk_initDev1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Device1"))
        item = self.table_chainCfg_statusBlk_initDev1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", " "))
        self.label_26.setText(_translate("MainWindow", "General Summary Information (Current Status)"))
        self.pushButton_statusRegReInit_3.setText(_translate("MainWindow", "RE-INITIALIZE"))
        self.pushButton_statusRegClear_3.setText(_translate("MainWindow", "CLERA COMM"))
        self.pushButton_statusRegInit_3.setText(_translate("MainWindow", "INITIALIZE"))
        self.pushButton_statusRegReadBack_3.setText(_translate("MainWindow", "READ BACK"))
        item = self.table_chainCfg_statusBlk_curDev0.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.table_chainCfg_statusBlk_curDev0.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_chainCfg_statusBlk_curDev0.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.table_chainCfg_statusBlk_curDev0.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.table_chainCfg_statusBlk_curDev0.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.table_chainCfg_statusBlk_curDev0.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Register"))
        item = self.table_chainCfg_statusBlk_curDev0.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expected {hex}"))
        item = self.table_chainCfg_statusBlk_curDev0.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actual {hex}"))
        item = self.table_chainCfg_statusBlk_curDev0.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", " "))
        __sortingEnabled = self.table_chainCfg_statusBlk_curDev0.isSortingEnabled()
        self.table_chainCfg_statusBlk_curDev0.setSortingEnabled(False)
        item = self.table_chainCfg_statusBlk_curDev0.item(0, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_statusBlk_curDev0.item(0, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Signle AFE)"))
        item = self.table_chainCfg_statusBlk_curDev0.item(0, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_statusBlk_curDev0.item(0, 3)
        item.setText(_translate("MainWindow", "A410"))
        item = self.table_chainCfg_statusBlk_curDev0.item(1, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_statusBlk_curDev0.item(1, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Dual, Device 0)"))
        item = self.table_chainCfg_statusBlk_curDev0.item(1, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_statusBlk_curDev0.item(1, 3)
        item.setText(_translate("MainWindow", "A410"))
        item = self.table_chainCfg_statusBlk_curDev0.item(2, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_statusBlk_curDev0.item(2, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Dual, Device 1)"))
        item = self.table_chainCfg_statusBlk_curDev0.item(2, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_statusBlk_curDev0.item(2, 3)
        item.setText(_translate("MainWindow", "A410"))
        self.table_chainCfg_statusBlk_curDev0.setSortingEnabled(__sortingEnabled)
        item = self.table_chainCfg_statusBlk_curDev1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.table_chainCfg_statusBlk_curDev1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_chainCfg_statusBlk_curDev1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.table_chainCfg_statusBlk_curDev1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.table_chainCfg_statusBlk_curDev1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Device1"))
        item = self.table_chainCfg_statusBlk_curDev1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", " "))
        self.label_25.setText(_translate("MainWindow", "Reset"))
        self.pushButton_statusRegReInit_2.setText(_translate("MainWindow", "RE-INITIALIZE"))
        self.pushButton_statusRegClear_2.setText(_translate("MainWindow", "CLERA COMM"))
        self.pushButton_statusRegInit_2.setText(_translate("MainWindow", "INITIALIZE"))
        self.pushButton_statusRegReadBack_2.setText(_translate("MainWindow", "READ BACK"))
        item = self.table_chainCfg_rstBlk_Dev0.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.table_chainCfg_rstBlk_Dev0.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.table_chainCfg_rstBlk_Dev0.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Register"))
        item = self.table_chainCfg_rstBlk_Dev0.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expected {hex}"))
        item = self.table_chainCfg_rstBlk_Dev0.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actual {hex}"))
        __sortingEnabled = self.table_chainCfg_rstBlk_Dev0.isSortingEnabled()
        self.table_chainCfg_rstBlk_Dev0.setSortingEnabled(False)
        item = self.table_chainCfg_rstBlk_Dev0.item(0, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.table_chainCfg_rstBlk_Dev0.item(0, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Signle AFE)"))
        item = self.table_chainCfg_rstBlk_Dev0.item(0, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.table_chainCfg_rstBlk_Dev0.item(0, 3)
        item.setText(_translate("MainWindow", "A410"))
        self.table_chainCfg_rstBlk_Dev0.setSortingEnabled(__sortingEnabled)
        item = self.table_chainCfg_rstBlk_Dev1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.table_chainCfg_rstBlk_Dev1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Device1"))
        __sortingEnabled = self.table_chainCfg_rstBlk_Dev1.isSortingEnabled()
        self.table_chainCfg_rstBlk_Dev1.setSortingEnabled(False)
        item = self.table_chainCfg_rstBlk_Dev1.item(0, 0)
        item.setText(_translate("MainWindow", "0000"))
        self.table_chainCfg_rstBlk_Dev1.setSortingEnabled(__sortingEnabled)
