# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pb01_dan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1706, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #a0a0a0; /* 设置背景颜色为灰色 */\n"
"    border-radius: 10px; /* 设置边框圆角的半径为10px */\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_21 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(0, 20))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_21.setStyleSheet("font: 12pt \"Calibri\";\n"
"font-weight: 600; /* 设置字体粗细为600 */")
        self.label_21.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        spacerItem = QtWidgets.QSpacerItem(447, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_48 = QtWidgets.QPushButton(self.frame)
        self.pushButton_48.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_48.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_48.setStyleSheet("QPushButton {\n"
"    background-color: #3072B3; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #145289; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 9pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5591D2; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E5A97; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_48.setObjectName("pushButton_48")
        self.horizontalLayout.addWidget(self.pushButton_48)
        self.pushButton_50 = QtWidgets.QPushButton(self.frame)
        self.pushButton_50.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_50.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_50.setStyleSheet("QPushButton {\n"
"    background-color: #3b8303; /* 按钮背景颜色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-width: 2px; /* 边框宽度 */\n"
"    border-radius: 10px; /* 边框圆角半径 */\n"
"    border-color: #326703; /* 边框颜色 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font: 9pt \"Calibri\"; /* 字体 */\n"
"    font-weight: 600; /* 字体粗细 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #459403; /* 悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #397303; /* 按下时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_50.setObjectName("pushButton_50")
        self.horizontalLayout.addWidget(self.pushButton_50)
        self.verticalLayout.addWidget(self.frame)
        self.tableWidget_uart_if_cfg1 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_uart_if_cfg1.setStyleSheet("QTableWidget {\n"
"    border: 2px solid white; /* 边框颜色与粗细调整为2px */\n"
"    gridline-color: white; /* 网格线颜色 */\n"
"    background-color: #f0f0f0; /* 单元格背景颜色 */\n"
"    font-family: \"Calibri\"; /* 单元格字体 */\n"
"    font-size: 10pt; /* 单元格字体大小 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* 表头背景颜色 */\n"
"    padding: 5px; /* 表头内边距 */\n"
"    border-style: none; /* 表头边框样式 */\n"
"    border-bottom: 5px solid white; /* 表头下边框宽度调整为2px */\n"
"    border-right: 2px solid white; /* 表头右边框宽度调整为2px */\n"
"    font-family: \"Calibri\"; /* 表头字体 */\n"
"    font-size: 10pt; /* 表头字体大小 */\n"
"    font-weight: 600; /* 表头字体粗细 */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f0f0f0; /* 角落按钮背景颜色 */\n"
"    /* 添加其他您需要的样式 */\n"
"}\n"
"")
        self.tableWidget_uart_if_cfg1.setObjectName("tableWidget_uart_if_cfg1")
        self.tableWidget_uart_if_cfg1.setColumnCount(14)
        self.tableWidget_uart_if_cfg1.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_uart_if_cfg1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_uart_if_cfg1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_uart_if_cfg1.setItem(2, 3, item)
        self.tableWidget_uart_if_cfg1.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget_uart_if_cfg1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1706, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_21.setText(_translate("MainWindow", "Cofigure Alert Register"))
        self.pushButton_48.setText(_translate("MainWindow", "CONFIGURE"))
        self.pushButton_50.setText(_translate("MainWindow", "READ BACK"))
        item = self.tableWidget_uart_if_cfg1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_uart_if_cfg1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_uart_if_cfg1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_uart_if_cfg1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidget_uart_if_cfg1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Register"))
        item = self.tableWidget_uart_if_cfg1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expected {hex}"))
        item = self.tableWidget_uart_if_cfg1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Actual {hex}"))
        item = self.tableWidget_uart_if_cfg1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "UARTDUAL"))
        item = self.tableWidget_uart_if_cfg1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "UARTLPBK"))
        item = self.tableWidget_uart_if_cfg1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "UARTWRPATH"))
        item = self.tableWidget_uart_if_cfg1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "TXUIDLEHIZ"))
        item = self.tableWidget_uart_if_cfg1.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "TXLIDLEHIZ"))
        item = self.tableWidget_uart_if_cfg1.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "UARTDCEN"))
        item = self.tableWidget_uart_if_cfg1.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "UARTALVCNTEN"))
        item = self.tableWidget_uart_if_cfg1.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "{logic Zero}"))
        item = self.tableWidget_uart_if_cfg1.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "DBLBUFEN"))
        item = self.tableWidget_uart_if_cfg1.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Reseved/SPI[6:0]"))
        __sortingEnabled = self.tableWidget_uart_if_cfg1.isSortingEnabled()
        self.tableWidget_uart_if_cfg1.setSortingEnabled(False)
        item = self.tableWidget_uart_if_cfg1.item(0, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.tableWidget_uart_if_cfg1.item(0, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Signle AFE)"))
        item = self.tableWidget_uart_if_cfg1.item(0, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.tableWidget_uart_if_cfg1.item(0, 3)
        item.setText(_translate("MainWindow", "A410"))
        item = self.tableWidget_uart_if_cfg1.item(1, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.tableWidget_uart_if_cfg1.item(1, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Dual, Device 0)"))
        item = self.tableWidget_uart_if_cfg1.item(1, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.tableWidget_uart_if_cfg1.item(1, 3)
        item.setText(_translate("MainWindow", "A410"))
        item = self.tableWidget_uart_if_cfg1.item(2, 0)
        item.setText(_translate("MainWindow", "0x10"))
        item = self.tableWidget_uart_if_cfg1.item(2, 1)
        item.setText(_translate("MainWindow", "UIFCFG (Dual, Device 1)"))
        item = self.tableWidget_uart_if_cfg1.item(2, 2)
        item.setText(_translate("MainWindow", "2600"))
        item = self.tableWidget_uart_if_cfg1.item(2, 3)
        item.setText(_translate("MainWindow", "A410"))
        self.tableWidget_uart_if_cfg1.setSortingEnabled(__sortingEnabled)
