# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temporary.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QRadioButton

class ToggleRadioButton(QRadioButton):
    def mousePressEvent(self, e):
        if self.isChecked():
            # Temporarily disable auto-exclusive to allow unchecking.
            self.setAutoExclusive(False)
            self.setChecked(False)
            # Re-enable auto-exclusive for normal radio button behavior.
            self.setAutoExclusive(True)
        else:
            # Standard behavior for checking the radio button.
            super().mousePressEvent(e)

class MyApp(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        layout = QVBoxLayout()

        self.toggleButton = ToggleRadioButton("Click me!")
        self.toggleButton.setChecked(False)
        layout.addWidget(self.toggleButton)

        self.setLayout(layout)
        self.setWindowTitle('Toggle RadioButton Example')
        self.setGeometry(300, 300, 300, 200)
        self.show()

if __name__ == '__main__':
    import sys
    app = QApplication(sys.argv)
    ex = MyApp()
    sys.exit(app.exec_())
