# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temporary.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# print(hex(10)[2:].upper().zfill(6))

def hex_to_bin(hex_str):
    # 将16进制转换为2进制，移除"0b"前缀，并填充零以保持字节格式
    bin_str = bin(int(hex_str, 16))[2:].zfill(len(hex_str) * 4)
    return bin_str

hexStr = '253f'

print(hex_to_bin(hexStr[0:2]))

polCfgText = '12ab'
print(hex_to_bin(polCfgText[0:8]))

#
# print(bin(int(hexStr[0:2],16))[2:].zfill(8))
# print(bin(int(hexStr[2:],16))[2:].zfill(8))
